# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('motor', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicule_year', models.CharField(blank=True, max_length=5, null=True)),
                ('seat_number', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleType'),
        ),
    ]
