# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentOxigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
    ]
