# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_equipamentoxigen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='FireCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='UserAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
                ('leader', models.CharField(choices=[('F', 'NO'), ('T', 'SI')], default='F', max_length=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='VehicleEmergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVE'), ('E', 'ELIMINATED')], default='A', max_length=1)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Emergency')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.AddField(
            model_name='userassistance',
            name='vehicle_emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.VehicleEmergency'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='emergency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.EmergencyType'),
        ),
    ]
